In [51]:
# NIM/Nama  : 16521432/Syafiq Ziyadul Arifin
# Tanggal   : 1 Desember 2021
# Deskripsi : Diberikan data harga rumah yang disewakan di Airbnb di Singapura
# Judul     : Problem 1 Praktikum 5 Praktikum Pengenalan Komputasi Pengantar 2021-2022

# Kamus
# import pandas as pd: mengimpor library pandas dan meng-assign pandas sebagai pd untuk digunakan
# df: variabel yang membaca data "P05-03.csv"
# .read_csv(): membaca data
# .value_counts(): membaca banyaknya data sesuai dengan nilai tiap data
# .sort_values(): mengurutkan data sesuai dengan kolom tertentu
# ascending: menentukan cara mengurutkan data (menurun atau menaik)
# .loc(): menampilkan data tertentu
# .corr(): korelasi data

# Mulai

# Kita mulai dengan mengimpor modul pandas dan data csv tersebut
import pandas as pd
df = pd.read_csv("C:/Users/safiq/Downloads/P05-03.csv")

In [52]:
# 1. Banyaknya rumah masing-masing neighbourhood
df["neighbourhood"].value_counts()

Kallang                    1043
Geylang                     994
Novena                      537
Rochor                      536
Outram                      477
Bukit Merah                 470
Downtown Core               428
Bedok                       373
River Valley                362
Queenstown                  266
Tanglin                     210
Singapore River             175
Marine Parade               171
Jurong West                 153
Orchard                     136
Newton                      134
Bukit Timah                 131
Jurong East                 118
Hougang                     109
Clementi                    102
Toa Payoh                   101
Pasir Ris                    71
Serangoon                    69
Sengkang                     67
Woodlands                    67
Bukit Batok                  65
Tampines                     64
Museum                       63
Choa Chu Kang                63
Ang Mo Kio                   58
Bishan                       57
Yishun                       53
Punggol                      43
Sembawang                    41
Bukit Panjang                34
Central Water Catchment      34
Southern Islands             17
Sungei Kadut                  5
Western Water Catchment       4
Mandai                        3
Tuas                          1
Marina South                  1
Lim Chu Kang                  1
Name: neighbourhood, dtype: int64

In [53]:
# 2. Jumlah malam penyewaan minimum terbanyak
df["minimum_nights"].value_counts()[:1]

1    2089
Name: minimum_nights, dtype: int64

In [54]:
# 3. 5 data dengan posisi paling selatan (longitude minimum)
df.sort_values("latitude", ascending=1)[:5]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
5765,31776450,Singapore's Most Exclusive Penthouse,93747362,Susana,Central Region,Southern Islands,1.24387,103.84246,Entire home/apt,865,90,0,NaN,NaN,1,365
1215,10638837,Luxury SENTOSA Condo within a Marina!,51190711,Cheez,Central Region,Southern Islands,1.24391,103.83915,Entire home/apt,481,3,2,2018-04-01,0.10,2,0
5714,31527262,"Jo's Place Sentosa, a Unique & Romantic Boat Stay",170561338,Josephine,Central Region,Southern Islands,1.24526,103.83999,Entire home/apt,200,1,33,2019-08-22,5.13,1,155
6387,33601064,Staycation on Yacht\nPer night $ (Phone number...,253196803,Carol,Central Region,Southern Islands,1.24627,103.84063,Entire home/apt,1200,1,0,NaN,NaN,1,362
3554,22987047,The Club Residences - 3 BR Suite (Monthly Stay),84411185,Darren,Central Region,Southern Islands,1.24847,103.82389,Entire home/apt,700,30,0,NaN,NaN,6,361

In [55]:
# 4. Rumah yang ada di neighbourhood group West Region
df.loc[df["neighbourhood_group"] == "West Region"]

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
24,553229,Comfortable Condo Room - Boon Lay MRT,1030128,Lena,West Region,Jurong West,1.34135,103.71139,Private room,53,2,23,2019-08-11,0.27,3,345
58,1060046,S$950/mth spacious room for short/long term lease,5748910,Sarah,West Region,Bukit Panjang,1.38123,103.76874,Private room,49,3,15,2019-06-01,0.20,2,131
89,1646909,"Cozy room, convenient location",8739736,Serene,West Region,Bukit Batok,1.34126,103.75992,Private room,82,14,0,NaN,NaN,1,365
105,1813277,Student Guardianship & Homestay,9497281,Skye,West Region,Choa Chu Kang,1.38717,103.74256,Private room,60,183,0,NaN,NaN,2,365
122,2033483,"★2+1condo next to MRT, mall & more★",9497281,Skye,West Region,Choa Chu Kang,1.38768,103.74476,Entire home/apt,118,10,0,NaN,NaN,2,294
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7752,37798739,near Clementi MRT female only,157856583,Elyssa,West Region,Clementi,1.30677,103.76224,Private room,56,1,1,2019-08-17,1.00,1,120
7782,37887437,西部文理有保安的公寓楼下就是地铁站+巴士总站+商场｡南洋理工大学NUS附近｡,183511167,琳琳,West Region,Jurong West,1.33748,103.70597,Private room,90,1,0,NaN,NaN,8,357
7856,38007847,Spacious 3 bedroom at Perfect location,238891646,Neha,West Region,Clementi,1.31473,103.75964,Entire home/apt,350,3,0,NaN,NaN,34,364
7867,38028286,Nearby NUS big common room,288546201,Xiaoqing,West Region,Clementi,1.30650,103.76732,Private room,43,3,0,NaN,NaN,1,5
7900,38102097,环境优雅的公寓,286260560,Bo,West Region,Bukit Batok,1.35654,103.76028,Private room,90,3,0,NaN,NaN,1,83

In [56]:
# 5. Koefisien korelasi antara banyak review di aplikasi dengan banyaknya hari ketersediaan rumah dalam satu tahun
df["number_of_reviews"].corr(df["availability_365"])
# Karena koefisien korelasinya mendekati 0, maka banyak review di aplikasi dengan banyaknya hari ketersediaan rumah dalam satu tahun
# tidak berkorelasi antara satu dengan yang lain

-0.0666580643449999